version: "3"

volumes:
  postalAssets:

services:
  nginx:
    image: nginx
    container_name: postal_nginx
    ports: ["8080:8080"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - postalAssets:/opt/postal/public
  mysql:
    image: mariadb:10
    container_name: postal_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: postal_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=/postal
  postal:
    build: .
    container_name: postal
    command: ./wrapper.sh run
    ports: ["25:25", "5000:5000"]
    depends_on: [nginx, mysql, rabbitmq]
    volumes:
      - postalAssets:/opt/postal/public
    environment:
      - POSTAL_HOST="localhost:8080"
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=postal
      - RABBITMQ_DEFAULT_USER=postal
      - RABBITMQ_DEFAULT_PASS=changeme
      - RABBITMQ_DEFAULT_VHOST=postal
